services:
  db:
    image: postgres
    container_name: library
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aru
      - POSTGRES_PASSWORD=test
    volumes:
      - library_db=/var/lib/postgresql/data 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8880:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: "user-name@domain-name.com"
      PGADMIN_DEFAULT_PASSWORD: "strong-password"
    volumes:
      - pgadmin_data=/var/lib/pgadmin-data

volumes:
  local_pgdata:
  pgadmin-data: